//check if matrix is magic square and even generate one

//based on the Siamese method for odd numbered magic squares

//https://en.wikipedia.org/wiki/Siamese_method

//METHOD:
/*First, an arithmetic progression has to be chosen (such as the simple progression 1,2,3,4,5,6,7,8,9 for a square with three rows and columns (the Lo Shu square)).
*Then, starting from the central box of the first row with the number 1 (or the first number of any arithmetic progression), the fundamental movement for filling the boxes is diagonally up and right (↗), one step at a time. When a move would leave the square, it is wrapped around to the last row or first column, respectively.
*If a filled box is encountered, one moves vertically down one box (↓) instead, then continuing as before. 
*/

#include <stdio.h>
#include <stdbool.h>

bool chkMagicSquare(int rows, int columns, int arr[rows][columns]){
    int diagonalSum1 = 0, diagonalSum2 = 0;
    for(int i = 0; i < rows; i++){
        diagonalSum1 += arr[i][i];
        diagonalSum2 += arr[i][rows - 1 - i];
    }
    if(diagonalSum1 != diagonalSum2) return false;

    for(int row = 0; row < rows; row++){
        int rowSum = 0, colSum = 0;
        for(int column = 0; column < columns; column++){
            rowSum += arr[row][column];
            colSum += arr[column][row];
        }
        if(rowSum != colSum || colSum != diagonalSum1) return false;    
    }
    return true;
}

void generateMagicSquare(int n, int arr[n][n]) {
    // Initialize all positions to 0
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            arr[i][j] = 0;
        }
    }

    int num = 1;
    int row = 0;
    int col = n / 2;
    int nSquared = n * n;

    while (num <= nSquared) {
        arr[row][col] = num++;
        //wrap around
        int newRow = (row - 1 + n) % n;
        int newCol = (col + 1) % n;

        if (arr[newRow][newCol] != 0) {
            //move down if filled cell is encountered
            row = (row + 1) % n;
        } else {
            row = newRow;
            col = newCol;
        }
    }
}

void printMatrix(int n, int arr[n][n]) {
    for(int row = 0; row < n; row++){
        for(int column = 0; column < n; column++){
            printf("%4d ", arr[row][column]);
        }
        printf("\n");
    }
}

int main(){
    int n;
    printf("Enter the size of the magic square (odd number): ");
    scanf("%d", &n);

    int magicArr[n][n], maxelement = n * n;
    generateMagicSquare(n, magicArr);

    printf("The magic square generated by the algorithm:\n\n");
    printMatrix(n, magicArr);

    if(chkMagicSquare(n, n, magicArr)) printf("\nThe generated matrix is a magic square where each rwo, column and diagonal sums upto %d\n", (maxelement * (maxelement + 1))/(2 * n)  );
    else printf("\nThe algorithm generated a magic square incorrectly\nPerhaps the size of the square was incorrectly entered as even, check again.");

    return 0;
}
